//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKWindowFormApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// マウスがクリック中かどうか
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("マウスがクリック中かどうか")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MOUSE_FLAG {
            get {
                return ((bool)(this["MOUSE_FLAG"]));
            }
            set {
                this["MOUSE_FLAG"] = value;
            }
        }
        
        /// <summary>
        /// ペンの色
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ペンの色")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PEN_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["PEN_COLOR"]));
            }
            set {
                this["PEN_COLOR"] = value;
            }
        }
        
        /// <summary>
        /// 現在のクリックした位置
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("現在のクリックした位置")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PREV_POINT {
            get {
                return ((global::System.Drawing.Point)(this["PREV_POINT"]));
            }
            set {
                this["PREV_POINT"] = value;
            }
        }
        
        /// <summary>
        /// 線の太さ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("線の太さ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PEN_BOLD {
            get {
                return ((int)(this["PEN_BOLD"]));
            }
            set {
                this["PEN_BOLD"] = value;
            }
        }
        
        /// <summary>
        /// 図形モードのインデックス
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("図形モードのインデックス")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SHAPE_MODE_INDEX {
            get {
                return ((int)(this["SHAPE_MODE_INDEX"]));
            }
            set {
                this["SHAPE_MODE_INDEX"] = value;
            }
        }
        
        /// <summary>
        /// 保存しているファイル名
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("保存しているファイル名")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_PATH {
            get {
                return ((string)(this["FILE_PATH"]));
            }
            set {
                this["FILE_PATH"] = value;
            }
        }
        
        /// <summary>
        /// アプリケーションの名前
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリケーションの名前")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("お絵描きツール")]
        public string APP_NAME {
            get {
                return ((string)(this["APP_NAME"]));
            }
            set {
                this["APP_NAME"] = value;
            }
        }
    }
}
